version: "3"

services:
  mitmproxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.mitmproxy:/home/mitmproxy/.mitmproxy
    ports:
      - 8080:8080
    command: [
      "mitmdump", "-s", "/scripts/elasticArchive.py",
      "--set", "elasticsearch_URL=http://elasticsearch:9200/mitmproxy/_doc",
      "--set", "storeBinaryContent=true",
    ]


  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
